version: '2.1'

services:
  discovery:
    build: .
    cap_add:
     - NET_ADMIN
    network_mode: host
    volumes:
     - /dev/net:/dev/net
     - /var/run/docker.sock:/var/run/docker.sock
  helloworld:
    build:
      context: .
      dockerfile: helloworld.dockerfile
    labels:
      anycast.address: "192.0.2.1"
    ports:
     - "192.0.2.1:80:80"
    depends_on:
     - discovery
